### ISSUE TITLE
PI port: post merge work

### ISSUE THREAD

**Issue by aarongreig** [intel/llvm#14598]
I'm creating this issue to capture any work that will need to be done post-merge, inevitably we've had to leave some stuff unfinished to make the ABI breaking window.

**Tasks from review**

- [ ] rename UR xpti stream to ur.call - first raised in [this comment](https://github.com/intel/llvm/pull/14145#discussion_r1650824996)
- [ ] implement UR_LOG_TRACING env var in UR instead of sycl RT, currently it's implemented in ur.hpp - first raised in [this comment](https://github.com/intel/llvm/pull/14145#discussion_r1650933889)
- [ ] rename SYCL_ENABLE_PLUGINS accounting for the different in UR terminology (PLUGIN -> ADAPTER) - first raised in [this comment](https://github.com/intel/llvm/pull/14145#discussion_r1670447784)
- [ ] create new target component for unified-runtime, currently UR libs are installed as part of `COMPONENT level-zero-sycl-dev` - see [this comment](https://github.com/intel/llvm/pull/14145#discussion_r1672015827)
- [ ] review all documentation pertaining to PI and either remove it, update it or re-direct it to point at docs in the UR repo - mentioned [here](https://github.com/intel/llvm/pull/14145#discussion_r1678834425)

**Regressions**

This is a placeholder that will soon be the list of regressions we need to fix

**Comment by omarahmed1111** [comment]
` AddressSanitizer` should be unrelated to this as they fail with the same failure locally for me with the sycl branch, and by looking on github CI, they should be reported as `unsupported`. So, they should be re-enabled once the PR is merged.

**Comment by KornevNikita** [comment]
@omarahmed1111 could you please clarify the status of these tests?
```
 AddressSanitizer/common/kernel-debug.cpp
 AddressSanitizer/multiple-reports/multiple_kernels.cpp
 AddressSanitizer/multiple-reports/one_kernel.cpp
 AddressSanitizer/use-after-free/quarantine-free.cpp
```
They're failing in Nightly, but there is no issue for them. Should we create one?

**Comment by aarongreig** [comment]
Ah it seems we missed xfailing those, they are affected by the same issue as https://github.com/intel/llvm/issues/14658. We do have a fix https://github.com/oneapi-src/unified-runtime/pull/1883 but I think we're prioritizing merging feature PRs for now so I'll open a PR to xfail them to unblock the nightly.

**Comment by KornevNikita** [comment]
> Ah it seems we missed xfailing those, they are affected by the same issue as #14658. We do have a fix [oneapi-src/unified-runtime#1883](https://github.com/oneapi-src/unified-runtime/pull/1883) but I think we're prioritizing merging feature PRs for now so I'll open a PR to xfail them to unblock the nightly.

Ok, good.

After port there're also failures in SYCL-CTS: https://github.com/intel/llvm/actions/runs/10137365848/job/28027872635
All like this:

```
  /__w/llvm/llvm/khronos_sycl_cts/tests/queue/queue_shortcuts_explicit_core.cpp:30: FAILED:
    {Unknown expression after the reported line}
  due to unexpected exception with messages:
    for type "char": 
    SYCL exception
    with category name: 'sycl'
    with code: 'runtime'
    with code raw value: '1'
    with code message: 'SYCL Error'
    with what: 'Native API failed. Native API returns: 45
    (UR_RESULT_ERROR_INVALID_ARGUMENT)'
```
Do you know if it's some known issue?

**Comment by aarongreig** [comment]
It isn't a known problem, I've added an issue to the OP to investigate. I have seen fails like that before so it's very likely that a fix for one of the remaining e2e regressions will also fix the cts.

**Comment by uditagarwal97** [comment]
FYI, while enabling E2E tests on PVC (https://github.com/intel/llvm/pull/14720), I see a failure in `Matrix/SG32/element_wise_all_ops.cpp`, which could be related to PI2UR work. Similar to the failure in `Matrix/element_wise_all_ops.cpp` (https://github.com/intel/llvm/issues/14795).

**Comment by kbenzie** [comment]
> > Ah it seems we missed xfailing those, they are affected by the same issue as #14658. We do have a fix [oneapi-src/unified-runtime#1883](https://github.com/oneapi-src/unified-runtime/pull/1883) but I think we're prioritizing merging feature PRs for now so I'll open a PR to xfail them to unblock the nightly.
> 
> Ok, good.
> 
> After port there're also failures in SYCL-CTS: https://github.com/intel/llvm/actions/runs/10137365848/job/28027872635 All like this:
> 
> ```
>   /__w/llvm/llvm/khronos_sycl_cts/tests/queue/queue_shortcuts_explicit_core.cpp:30: FAILED:
>     {Unknown expression after the reported line}
>   due to unexpected exception with messages:
>     for type "char": 
>     SYCL exception
>     with category name: 'sycl'
>     with code: 'runtime'
>     with code raw value: '1'
>     with code message: 'SYCL Error'
>     with what: 'Native API failed. Native API returns: 45
>     (UR_RESULT_ERROR_INVALID_ARGUMENT)'
> ```
> 
> Do you know if it's some known issue?

@KornevNikita https://github.com/intel/llvm/pull/14873 should fix the SYCL CTS, it has been confirmed to fix 2 of the 3 failures at the time of writing but the run has not completed.

**Comment by KornevNikita** [comment]
@kbenzie thanks, I'll check it manually

**Comment by KornevNikita** [comment]
> @kbenzie thanks, I'll check it manually

yep, that helps, thanks.
